export const themes = [
  {
    id: "dracula",
    label: "Dracula",
    themeType: "dark",
    selected: false,
    colors: {
      background: "#282a36",
      titleBar: "#1a1c25",
      darkGrey: "#2a2d31",
      grey: "#242632",
      lightGrey: "#2c303e",
      primaryText: "#f8f8f2",
      secondaryText: "#aeafb0",
      firstColor: "#8eebfc",
      secondColor: "#aa8cdc",
      thirdColor: "#50fa7c",
      fourthColor: "#edf68a",
      fifthColor: "#e770b6",
      scrollbar: "hsla(223, 18%, 23%, .75)",
      layoutBorder: "hsla(0, 0%, 0%, 0.75)",
    },
  },
  {
    id: "tomorrow",
    label: "Tomorrow",
    themeType: "light",
    selected: false,
    colors: {
      background: "#ffffff",
      titleBar: "#e8e8e8",
      darkGrey: "#2a2d31",
      grey: "hsl(109, 0%, 87%)",
      lightGrey: "#e8e8e8",
      primaryText: "#4d4d4c",
      secondaryText: "#6c6c6c",
      firstColor: "#8959a8",
      secondColor: "#4271ad",
      thirdColor: "#718c01",
      fourthColor: "#eab702",
      fifthColor: "#8959a8",
      scrollbar: "#f1f1f1",
      layoutBorder: "hsla(100, 100%, 100%, 1)",
    },
  },
  {
    id: "atomOneDark",
    label: "Atom One Dark",
    themeType: "dark",
    selected: false,
    colors: {
      background: "#282c34",
      titleBar: "#242a31",
      darkGrey: "#282c34",
      grey: "#242a31",
      lightGrey: "#39404b",
      primaryText: "#aab1be",
      secondaryText: "#8a8a8b",
      firstColor: "#be6770",
      secondColor: "#57bec9",
      thirdColor: "#8db573",
      fourthColor: "#be9268",
      fifthColor: "#c678dd",
      scrollbar: "#39404b",
      layoutBorder: "#242a31",
    },
  },
  {
    id: "atomOneLight",
    label: "Atom One Light",
    themeType: "light",
    selected: false,
    colors: {
      background: "#fafafa",
      titleBar: "#ededee",
      darkGrey: "#282c34",
      grey: "hsl(234, 3%, 90%)",
      lightGrey: "#ededee",
      primaryText: "#5b5d63",
      secondaryText: "#777777",
      firstColor: "#e6665a",
      secondColor: "#73c0dd",
      thirdColor: "#50a14f",
      fourthColor: "#c09c52",
      fifthColor: "#a726a4",
      scrollbar: "#f2f2f2",
      layoutBorder: "#ededee",
    },
  },
  {
    id: "far",
    label: "Far",
    themeType: "fun",
    selected: false,
    colors: {
      background: "#010880",
      titleBar: "#0039a3",
      darkGrey: "#282c34",
      grey: "#0039a3",
      lightGrey: "#206dd2",
      primaryText: "#00f5fa",
      secondaryText: "#f5f7fc",
      firstColor: "#f3c8e4",
      secondColor: "#00f6fb",
      thirdColor: "#fffe04",
      fourthColor: "#fffe04",
      fifthColor: "#ffffff",
      scrollbar: "#206dd2",
      layoutBorder: "#0039a3",
    },
  },
  {
    id: "shadesOfPurple",
    label: "Shades of Purple",
    themeType: "fun",
    selected: false,
    colors: {
      background: "#2d2c57",
      titleBar: "#1e2248",
      darkGrey: "#1f1e3f",
      grey: "#23274d",
      lightGrey: "hsl(230, 39%, 38%)",
      primaryText: "#e3dfff",
      secondaryText: "#938dce",
      firstColor: "#f3c8e4",
      secondColor: "#a9f598",
      thirdColor: "#49c219",
      fourthColor: "#9ffbfb",
      fifthColor: "#fb9e02",
      scrollbar: "#aba4ec",
      layoutBorder: "#23274d",
    },
  },
]
